config/routes.rb
#-------------------------------------------------------------------------------------------#
# Redmine CMDB plugin: Configuration Management DataBase                                    #
# Copyright (C) 2025 Franz Apeltauer                                                        #
#                                                                                           #
# This program is free software: you can redistribute it and/or modify it under the terms   #
# of the GNU Affero General Public License as published by the Free Software Foundation,    #
# either version 3 of the License, or (at your option) any later version.                   #
#                                                                                           #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; #
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. #
# See the GNU Affero General Public License for more details.                               #
#                                                                                           #
# You should have received a copy of the GNU Affero General Public License                  #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.                    #
#-------------------------------------------------------------------------------------eohdr-#
# Purpose: Route definitions for the CMDB plugin.
#          Defines RESTful routes for locations, CI classes, CIs, lifecycle statuses, external systems,
#          location hierarchy management, and CI-Issue associations.

Rails.application.routes.draw do
  # CMDB main routes
  resources :cmdb do
    collection do
      get 'tree_data'
      get 'info'
      get 'new_location', action: :new_location
      get 'location/:id', action: :show_location, as: :show_location
      post 'location', action: :create_location
      put 'location/:id', action: :update_location
      delete 'location/:id', action: :destroy_location
      get 'new_ci_class', action: :new_ci_class
      get 'ci_class/:id', action: :show_ci_class, as: :show_ci_class
      post 'ci_classes', action: :create_ci_class
      put 'ci_classes/:id', action: :update_ci_class
      delete 'ci_classes/:id', action: :destroy_ci_class
      get 'new_ci', action: :new_ci
      get 'ci/:id', action: :show_ci, as: :show_ci
      post 'cis', action: :create_ci
      put 'cis/:id', action: :update_ci
      delete 'cis/:id', action: :destroy_ci
      get 'new_lifecycle_status', action: :new_lifecycle_status
      get 'lifecycle_status/:id', action: :show_lifecycle_status, as: :show_lifecycle_status
      post 'lifecycle_statuses', action: :create_lifecycle_status
      put 'lifecycle_statuses/:id', action: :update_lifecycle_status
      delete 'lifecycle_statuses/:id', action: :destroy_lifecycle_status
      get 'new_ext_sys', action: :new_ext_sys
      get 'ext_sys/:id', action: :show_ext_sys, as: :show_ext_sys
      post 'external_systems', action: :create_ext_sys
      put 'external_systems/:id', action: :update_ext_sys
      delete 'external_systems/:id', action: :destroy_ext_sys
    end
  end

  # Basic data routes (without namespace)
  scope :cmdb_basic_data do
    get '/', to: 'cmdb_basic_data#index', as: :cmdb_basic_data
    get '/location_hierarchies/new_hierarchy', to: 'cmdb_basic_data#new_hierarchy', as: :new_cmdb_basic_data_hierarchy
    get '/location_hierarchies/:id', to: 'cmdb_basic_data#show', as: :cmdb_basic_data_location_hierarchy
    post '/location_hierarchies', to: 'cmdb_basic_data#create', as: :cmdb_basic_data_location_hierarchies
    put '/location_hierarchies/:id', to: 'cmdb_basic_data#update'
    delete '/location_hierarchies/:id', to: 'cmdb_basic_data#destroy'

    # Seed data management routes
    get '/seed_data_management', to: 'cmdb_basic_data#show_seed_data_management', as: :seed_data_management_cmdb_basic_data
    post '/seed_data/add', to: 'cmdb_basic_data#add_seed_data', as: :add_seed_data_cmdb_basic_data
    post '/seed_data/remove_unused', to: 'cmdb_basic_data#remove_unused_seed_data', as: :remove_unused_seed_data_cmdb_basic_data
  end

  # CI-Issue integration routes
  resources :issues, only: [] do
    get 'cis/available', to: 'issue_cis#available_cis', as: :available_cis
    resources :cis, controller: 'issue_cis', only: [:create, :destroy]
  end
end

app/helpers/cmdb_helper.rb
#-------------------------------------------------------------------------------------------#
# Redmine CMDB plugin: Configuration Management DataBase                                    #
# Copyright (C) 2025 Franz Apeltauer                                                        #
#                                                                                           #
# This program is free software: you can redistribute it and/or modify it under the terms   #
# of the GNU Affero General Public License as published by the Free Software Foundation,    #
# either version 3 of the License, or (at your option) any later version.                   #
#                                                                                           #
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; #
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. #
# See the GNU Affero General Public License for more details.                               #
#                                                                                           #
# You should have received a copy of the GNU Affero General Public License                  #
# along with this program.  If not, see <https://www.gnu.org/licenses/>.                    #
#-------------------------------------------------------------------------------------eohdr-#
# Purpose: View helper methods for CMDB permission checks in views and controllers.
#          Provides convenient methods to check user's view, edit, and basic_data permissions.

module CmdbHelper
  # Checks if current user can view CMDB data.
  # Users with edit or edit_basic_data permissions can also view.
  # Returns: Boolean indicating if user has view access
  def can_view_cmdb?
    # Users who can edit can also view
    HrzCmdb::PermissionHelper.user_has_permission?(User.current, 'view_cmdb') ||
    HrzCmdb::PermissionHelper.user_has_permission?(User.current, 'edit_cmdb') ||
    HrzCmdb::PermissionHelper.user_has_permission?(User.current, 'edit_basic_data')
  end

  # Checks if current user can edit locations and CIs.
  # Returns: Boolean indicating if user has edit_cmdb permission
  def can_edit_cmdb?
    HrzCmdb::PermissionHelper.user_has_permission?(User.current, 'edit_cmdb')
  end

  # Checks if current user can edit basic data (CI classes, lifecycle statuses, external systems).
  # Returns: Boolean indicating if user has edit_basic_data permission
  def can_edit_basic_data?
    HrzCmdb::PermissionHelper.user_has_permission?(User.current, 'edit_basic_data')
  end

  # Formats documentation string as appropriate HTML link or text.
  # Parameter documentation: String documentation reference
  #   * 'tiki:PageName' ........... creates JavaScript link to TikiWiki page
  #   * 'https://...' ............. creates external link
  #   * plain text ................ wraps in span tag
  # Returns: HTML safe string (link or span element), or empty string if blank
  def format_documentation_link(documentation)
    return '' if documentation.blank?

    if documentation.starts_with?('tiki:')
      page_name = documentation.sub('tiki:', '')
      link_to documentation, "#", onclick: "HrzCmdb.openTiki('#{page_name}'); return false;",
              class: 'documentation-link', target: '_blank'
    elsif documentation =~ /\Ahttps?:\/\//
      link_to documentation, documentation, class: 'documentation-link', target: '_blank'
    else
      content_tag :span, documentation, class: 'documentation-text'
    end
  end

  # Generates breadcrumb navigation for a location showing all parent locations.
  # Parameter location: HrzcmLocation instance to generate breadcrumb for
  # Returns: HTML safe string with linked location names separated by ' > '
  def location_breadcrumb(location)
    parts = []
    current = location

    while current
      parts.unshift(link_to(current.b_name_abbr || current.b_name_full,
                           "#", onclick: "HrzCmdb.loadLocation(#{current.id}); return false;"))
      current = current.parent1
    end

    safe_join(parts, ' > ')
  end

  # Renders location select options grouped by hierarchy level.
  # Parameter selected_id: Integer ID of location to mark as selected (optional)
  # Parameter exclude_id: Integer ID of location to exclude from options (optional)
  # Returns: HTML safe string with optgroup elements containing location options
  def render_location_tree_options(selected_id = nil, exclude_id = nil)
    options = []

    HrzcmLocatHier.ordered_by_level.each do |hierarchy|
      options << content_tag(:optgroup, label: hierarchy.b_name_abbr) do
        locations = HrzcmLocation.for_type(hierarchy.id).ordered_by_b_name_abbr
        locations = locations.where.not(id: exclude_id) if exclude_id

        options_from_collection_for_select(locations, :id, :display_name, selected_id)
      end
    end

    safe_join(options)
  end

  # Returns appropriate icon HTML for a given CMDB item type.
  # Parameter type: String type identifier
  #   * 'folder' or 'location_with_children' ... folder icon 📁
  #   * 'page' or 'location' .................. page icon 📄
  #   * 'add' or 'new' ........................ add icon ➕
  #   * other ................................. default icon ▪
  # Returns: HTML safe span element with icon
  def cmdb_icon(type)
    case type
    when 'folder', 'location_with_children'
      content_tag :span, '📁', class: 'icon icon-folder'
    when 'page', 'location'
      content_tag :span, '📄', class: 'icon icon-page'
    when 'add', 'new'
      content_tag :span, '➕', class: 'icon icon-add'
    else
      content_tag :span, '▪', class: 'icon icon-default'
    end
  end

  # Generates JavaScript tag with i18n translations for client-side use.
  # Creates window.hrz_cmdb_translations object with common UI text strings.
  # Returns: HTML safe JavaScript tag setting window.hrz_cmdb_translations
  def cmdb_javascript_translations
    translations = {
      select_item: l('hrz_cmdb.select_item'),
      save: l('hrz_cmdb.buttons.save'),
      cancel: l('hrz_cmdb.buttons.cancel'),
      create: l('hrz_cmdb.buttons.create'),
      confirm_delete: l(:text_are_you_sure)
    }

    javascript_tag "window.hrz_cmdb_translations = #{translations.to_json};"
  end
end

app/views/cmdb/_ci_class_details.html.erb
<!-- ------------------------------------------------------------------------------------------- -->
<!--  Redmine CMDB plugin: Configuration Management DataBase                                     -->
<!--  Copyright (C) 2025 Franz Apeltauer                                                         -->
<!--                                                                                             -->
<!--  This program is free software: you can redistribute it and/or modify it under the terms    -->
<!--  of the GNU Affero General Public License as published by the Free Software Foundation,     -->
<!--  either version 3 of the License, or (at your option) any later version.                    -->
<!--                                                                                             -->
<!--  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  -->
<!--  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  -->
<!--  See the GNU Affero General Public License for more details.                                -->
<!--                                                                                             -->
<!--  You should have received a copy of the GNU Affero General Public License                   -->
<!--  along with this program.  If not, see <https://www.gnu.org/licenses/>.                     -->
<!-- -------------------------------------------------------------------------------------eohdr- -->
<%# Purpose: Detail view partial displaying CI class information including hierarchy position and metadata.
            Shows CI class attributes in a read-only format with edit/delete buttons. %>

<div class="ci-class-details">
  <h3><%= ci_class.b_name_abbr %></h3>

  <% if can_edit %>
    <%= form_tag "/cmdb/ci_classes/#{ci_class.id}", method: :put, id: 'ci-class-form', class: 'ci-class-form' do %>
      <div class="form-group">
        <%= label_tag :b_name_full, l('hrz_cmdb.fields.b_name_full') %>
        <div class="field-wrapper">
          <%= text_field_tag 'ci_class[b_name_full]', ci_class.b_name_full, class: 'form-control', maxlength: 120 %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :b_name_abbr, l('hrz_cmdb.fields.b_name_abbr') %>
        <div class="field-wrapper">
          <%= text_field_tag 'ci_class[b_name_abbr]', ci_class.b_name_abbr, class: 'form-control form-control-short', maxlength: 15 %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :b_key, l('hrz_cmdb.fields.b_key') %>
        <div class="field-wrapper">
          <%= text_field_tag 'ci_class[b_key]', ci_class.b_key, class: 'form-control form-control-short', required: true %>
          <span class="hint"><%= l('hrz_cmdb.hints.b_key_ci_class') %></span>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :j_sort, l('hrz_cmdb.fields.j_sort') %>
        <div class="field-wrapper">
          <%= number_field_tag 'ci_class[j_sort]', ci_class.j_sort, class: 'form-control form-control-short' %>
          <span class="hint"><%= l('hrz_cmdb.hints.j_sort') %></span>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :j_subclass_of_id, l('hrz_cmdb.fields.j_subclass_of') %>
        <div class="field-wrapper">
          <%= select_tag 'ci_class[j_subclass_of_id]',
                         options_for_select(
                           [[l('hrz_cmdb.select_ci_class'), '']] +
                           HrzcmCiClass.ordered_by_sort_and_abbr.where.not(id: ci_class.id).map { |c| ["#{c.b_name_abbr} - #{c.b_name_full}", c.id] },
                           ci_class.j_subclass_of_id
                         ),
                         class: 'form-control',
                         id: 'ci_class_j_subclass_of_id' %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :b_comment, l('hrz_cmdb.fields.b_comment') %>
        <div class="field-wrapper">
          <%= text_area_tag 'ci_class[b_comment]', ci_class.b_comment, class: 'form-control', rows: 5, maxlength: 10000 %>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag :b_url_doc, l('hrz_cmdb.fields.b_url_doc') %>
        <div class="field-wrapper">
          <div class="url-field-container">
            <%= text_field_tag 'ci_class[b_url_doc]', ci_class.b_url_doc, class: 'form-control url-field', maxlength: 1500 %>
            <span class="url-open-icon <%= ci_class.b_url_doc.blank? ? 'disabled' : '' %>"
                  data-url="<%= ci_class.b_url_doc %>"
                  title="<%= l('hrz_cmdb.buttons.open_url', default: 'Open URL') %>"></span>
          </div>
          <span class="hint"><%= l('hrz_cmdb.hints.b_url_doc') %></span>
        </div>
      </div>

      <fieldset class="status-info">
        <legend><%= l('hrz_cmdb.status_info.title') %></legend>
        <div class="status-info-content">
          <% if ci_class.persisted? %>
            <%= l('hrz_cmdb.status_info.record_id') %>: <%= ci_class.id %>
            <% if ci_class.creator.present? %>
              <%= l('hrz_cmdb.status_info.created_by') %>
              <span class="user-link" title="<%= "#{ci_class.creator.firstname} #{ci_class.creator.lastname}" %>"><%= ci_class.creator.login %></span>
              <%= l('hrz_cmdb.status_info.at') %> <%= format_time(ci_class.created_on) %><%= ci_class.updater.present? ? ',' : '.' %>
            <% end %>
            <% if ci_class.updater.present? %>
              <%= l('hrz_cmdb.status_info.updated_by') %>
              <span class="user-link" title="<%= "#{ci_class.updater.firstname} #{ci_class.updater.lastname}" %>"><%= ci_class.updater.login %></span>
              <%= l('hrz_cmdb.status_info.at') %> <%= format_time(ci_class.updated_on) %>.
            <% end %>
          <% else %>
            <%= l('hrz_cmdb.status_info.new_record') %>
          <% end %>
        </div>
      </fieldset>

      <div class="form-actions">
        <%= submit_tag l('hrz_cmdb.buttons.save'), class: 'button button-positive' %>
        <%= submit_tag l('hrz_cmdb.buttons.save_continue'), class: 'button', name: 'continue' %>
        <% if ci_class.persisted? %>
          <%= submit_tag l('hrz_cmdb.buttons.save_as_copy'), class: 'button', name: 'save_as_copy' %>
        <% end %>
        <% if ci_class.persisted? %>
          <%= link_to l('hrz_cmdb.buttons.delete'), "#", class: 'button button-negative',
                      onclick: "if (confirm('#{l('hrz_cmdb.confirm.delete_ci_class')}')) { HrzCmdb.deleteNode('ci_class', #{ci_class.id}); } return false;" %>
        <% end %>
        <%= link_to l('hrz_cmdb.buttons.cancel'), '#', class: 'button', onclick: 'HrzCmdb.clearDetails(); return false;' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cmdb/_ci_class_form.html.erb
<!-- ------------------------------------------------------------------------------------------- -->
<!--  Redmine CMDB plugin: Configuration Management DataBase                                     -->
<!--  Copyright (C) 2025 Franz Apeltauer                                                         -->
<!--                                                                                             -->
<!--  This program is free software: you can redistribute it and/or modify it under the terms    -->
<!--  of the GNU Affero General Public License as published by the Free Software Foundation,     -->
<!--  either version 3 of the License, or (at your option) any later version.                    -->
<!--                                                                                             -->
<!--  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  -->
<!--  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  -->
<!--  See the GNU Affero General Public License for more details.                                -->
<!--                                                                                             -->
<!--  You should have received a copy of the GNU Affero General Public License                   -->
<!--  along with this program.  If not, see <https://www.gnu.org/licenses/>.                     -->
<!-- -------------------------------------------------------------------------------------eohdr- -->
<%# Purpose: Form partial for creating and editing CI class entries in the hierarchy.
            Allows defining CI categories with parent class, sort order, and documentation. %>

<div class="ci-class-form-container">
  <h3><%= l('hrz_cmdb.ci_classes.new') %></h3>

  <%= form_tag '/cmdb/ci_classes', method: :post, id: 'new-ci-class-form', class: 'ci-class-form' do %>
    <div class="form-group">
      <%= label_tag :b_name_full, l('hrz_cmdb.fields.b_name_full') %>
      <div class="field-wrapper">
        <%= text_field_tag 'ci_class[b_name_full]', '', class: 'form-control', maxlength: 120 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_name_abbr, l('hrz_cmdb.fields.b_name_abbr') %>
      <div class="field-wrapper">
        <%= text_field_tag 'ci_class[b_name_abbr]', '', class: 'form-control form-control-short', maxlength: 15 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_key, l('hrz_cmdb.fields.b_key') %>
      <div class="field-wrapper">
        <%= text_field_tag 'ci_class[b_key]', '', class: 'form-control form-control-short', required: true %>
        <span class="hint"><%= l('hrz_cmdb.hints.b_key_ci_class') %></span>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :j_sort, l('hrz_cmdb.fields.j_sort') %>
      <div class="field-wrapper">
        <%= number_field_tag 'ci_class[j_sort]', 0, class: 'form-control form-control-short' %>
        <span class="hint"><%= l('hrz_cmdb.hints.j_sort') %></span>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :j_subclass_of_id, l('hrz_cmdb.fields.j_subclass_of') %>
      <div class="field-wrapper">
        <%= select_tag 'ci_class[j_subclass_of_id]',
                       options_for_select(
                         [[l('hrz_cmdb.select_ci_class'), '']] +
                         HrzcmCiClass.ordered_by_sort_and_abbr.map { |c| ["#{c.b_name_abbr} - #{c.b_name_full}", c.id] }
                       ),
                       class: 'form-control',
                       id: 'ci_class_j_subclass_of_id' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_comment, l('hrz_cmdb.fields.b_comment') %>
      <div class="field-wrapper">
        <%= text_area_tag 'ci_class[b_comment]', '', class: 'form-control', rows: 5, maxlength: 10000 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_url_doc, l('hrz_cmdb.fields.b_url_doc') %>
      <div class="field-wrapper">
        <div class="url-field-container">
          <%= text_field_tag 'ci_class[b_url_doc]', '', class: 'form-control url-field', maxlength: 1500 %>
          <span class="url-open-icon disabled" title="<%= l('hrz_cmdb.buttons.open_url', default: 'Open URL') %>"></span>
        </div>
        <span class="hint"><%= l('hrz_cmdb.hints.b_url_doc') %></span>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag l('hrz_cmdb.buttons.create'), class: 'button button-positive', name: 'create' %>
      <%= link_to l('hrz_cmdb.buttons.cancel'), '#', class: 'button', onclick: 'HrzCmdb.clearDetails(); return false;' %>
    </div>
  <% end %>
</div>

app/views/cmdb/_location_form.html.erb
<!-- ------------------------------------------------------------------------------------------- -->
<!--  Redmine CMDB plugin: Configuration Management DataBase                                     -->
<!--  Copyright (C) 2025 Franz Apeltauer                                                         -->
<!--                                                                                             -->
<!--  This program is free software: you can redistribute it and/or modify it under the terms    -->
<!--  of the GNU Affero General Public License as published by the Free Software Foundation,     -->
<!--  either version 3 of the License, or (at your option) any later version.                    -->
<!--                                                                                             -->
<!--  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  -->
<!--  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  -->
<!--  See the GNU Affero General Public License for more details.                                -->
<!--                                                                                             -->
<!--  You should have received a copy of the GNU Affero General Public License                   -->
<!--  along with this program.  If not, see <https://www.gnu.org/licenses/>.                     -->
<!-- -------------------------------------------------------------------------------------eohdr- -->
<%# Purpose: Form partial for creating and editing location entries.
            Allows setting location type, parent locations, names, and documentation links. %>

<div class="location-form-container">
  <h3><%= l('hrz_cmdb.locations.new') %></h3>

  <%= form_tag cmdb_index_path + '/location', method: :post, id: 'new-location-form', class: 'location-form' do %>
    <div class="form-group">
      <%= label_tag :b_name_full, l('hrz_cmdb.fields.b_name_full') %>
      <div class="field-wrapper">
        <%= text_field_tag 'location[b_name_full]', '', class: 'form-control', maxlength: 120 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_name_abbr, l('hrz_cmdb.fields.b_name_abbr') %>
      <div class="field-wrapper">
        <%= text_field_tag 'location[b_name_abbr]', '', class: 'form-control form-control-short', maxlength: 15 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_key, l('hrz_cmdb.fields.b_key') %>
      <div class="field-wrapper">
        <%= text_field_tag 'location[b_key]', '', class: 'form-control form-control-short' %>
        <span class="hint"><%= l('hrz_cmdb.hints.b_key_location') %></span>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :j_type_id, l('hrz_cmdb.fields.type') %>
      <div class="field-wrapper">
        <%= select_tag 'location[j_type_id]',
            options_from_collection_for_select(HrzcmLocatHier.ordered_by_level, :id, :b_name_abbr),
            prompt: l('hrz_cmdb.select_type'),
            class: 'form-control', required: true %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :j_part_of1_id, l('hrz_cmdb.fields.part_of1') %>
      <div class="field-wrapper">
        <%= select_tag 'location[j_part_of1_id]',
            options_from_collection_for_select(HrzcmLocation.ordered_by_b_name_abbr, :id, :display_name),
            include_blank: true,
            class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :j_part_of2_id, l('hrz_cmdb.fields.part_of2') %>
      <div class="field-wrapper">
        <%= select_tag 'location[j_part_of2_id]',
            options_from_collection_for_select(HrzcmLocation.ordered_by_b_name_abbr, :id, :display_name),
            include_blank: true,
            class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_comment, l('hrz_cmdb.fields.b_comment') %>
      <div class="field-wrapper">
        <%= text_area_tag 'location[b_comment]', '', class: 'form-control', rows: 5, maxlength: 10000 %>
      </div>
    </div>

    <div class="form-group">
      <%= label_tag :b_url_doc, l('hrz_cmdb.fields.b_url_doc') %>
      <div class="field-wrapper">
        <div class="url-field-container">
          <%= text_field_tag 'location[b_url_doc]', '', class: 'form-control url-field', maxlength: 1500 %>
          <span class="url-open-icon disabled" title="<%= l('hrz_cmdb.buttons.open_url', default: 'Open URL') %>"></span>
        </div>
        <span class="hint"><%= l('hrz_cmdb.hints.b_url_doc') %></span>
      </div>
    </div>

    <div class="form-actions">
      <%= submit_tag l('hrz_cmdb.buttons.create'), class: 'button button-positive', name: 'create' %>
      <%= link_to l('hrz_cmdb.buttons.cancel'), '#', class: 'button', onclick: 'HrzCmdb.clearDetails(); return false;' %>
    </div>
  <% end %>
</div>

app/views/cmdb/index.html.erb
<!-- ------------------------------------------------------------------------------------------- -->
<!--  Redmine CMDB plugin: Configuration Management DataBase                                     -->
<!--  Copyright (C) 2025 Franz Apeltauer                                                         -->
<!--                                                                                             -->
<!--  This program is free software: you can redistribute it and/or modify it under the terms    -->
<!--  of the GNU Affero General Public License as published by the Free Software Foundation,     -->
<!--  either version 3 of the License, or (at your option) any later version.                    -->
<!--                                                                                             -->
<!--  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  -->
<!--  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  -->
<!--  See the GNU Affero General Public License for more details.                                -->
<!--                                                                                             -->
<!--  You should have received a copy of the GNU Affero General Public License                   -->
<!--  along with this program.  If not, see <https://www.gnu.org/licenses/>.                     -->
<!-- -------------------------------------------------------------------------------------eohdr- -->
<%# Purpose: Main CMDB page with jsTree-based hierarchical navigation for locations, CI classes, CIs, and other entities.
            Provides the primary user interface for browsing and managing the CMDB structure. %>

<% html_title(l(:label_cmdb)) %>

<div id="cmdb-container">
  <h2><%= l(:label_cmdb) %></h2>

  <div class="cmdb-content">
    <div id="cmdb-sidebar" class="cmdb-sidebar">
      <div id="cmdb-tree-container" class="tree-container">
        <div class="tree-header">
          <span class="icon icon-folder"></span>
          <%= l('hrz_cmdb.locations.title') %>
        </div>
        <div id="cmdb-tree" class="tree-content">
          <!-- Tree will be loaded here via JavaScript -->
        </div>
      </div>
    </div>

    <div id="cmdb-main" class="cmdb-main">
      <div id="cmdb-details" class="cmdb-details">
        <!-- Details will be loaded here when selecting items -->
        <div class="no-selection">
          <%= l('hrz_cmdb.select_item') %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'hrz_cmdb', plugin: 'hrz_cmdb', cache: false %>
<%= stylesheet_link_tag 'hrz_cmdb', plugin: 'hrz_cmdb', cache: false %>

<script>
  $(document).ready(function() {
    HrzCmdb.init({
      treeDataUrl: '<%= tree_data_cmdb_index_path %>',
      canEdit: <%= @can_edit ? 'true' : 'false' %>,
      canEditBasicData: <%= @can_edit_basic_data ? 'true' : 'false' %>,
      tikiBaseUrl: '<%= Setting.plugin_hrz_cmdb['tiki_base_url'].to_s.html_safe %>'
    });
  });
</script>